# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Trans_EM_rcpp <- function(Y, CI, X, RHO) {
    .Call('_AssoTest_Trans_EM_rcpp', PACKAGE = 'AssoTest', Y, CI, X, RHO)
}

